name: "Structr start and deploy action"
description: "Deploys a Structr and Neo4j stack into an action runner and imports a given Structr webapp."

branding:
  icon: arrow-down-circle
  color: green

inputs:
  structr-version:
    description: "The version of Structr to start"
    required: true
    default: "4.2.0"
  neo4j-version:
    description: "The version of Neo4j to start"
    required: true
    default: "4.4"
  structr-webapp-path:
    description: "The path to the Structr webapp folder. Defaults to <github.workspace>/webapp"  
    required: true
    default: "${{ github.workspace }}/webapp"
  structr-license:
    description: "A valid Structr license key"
    required: false
    default: ""
  structr-conf-file:
    description: "A custom structr.conf file used for the deployment"
    required: false
    default: ""
  

runs:
  using: "composite"
  steps:
    - name: Print configuration
      run: echo "Running Structr:${{ inputs.structr-version }} with Neo4j:${{ inputs.neo4j-version }} and deploying from ${{ inputs.structr-webapp-path }}"
      shell: bash

    - name: Start Structr and Neo4j
      env:
          NEO4j_VERSION: ${{ inputs.neo4j-version }}
          STRUCTR_VERSION: ${{ inputs.structr-version }}
          STRUCTR_WEBAPP_PATH: ${{ inputs.structr-webapp-path }}
          STRUCTR_LICENSE: ${{ inputs.structr-license }}
          STRUCTR_CONF_FILE: ${{ inputs.structr-conf-file }}
      run: >-        
        ./setup_environment.sh ${{ github.action_path }} &&
        docker-compose up -d      
        
      shell: bash      

    - name: Deploy given webapp
      run: cd ${{ github.action_path }} && ./deploy.sh
      shell: bash