name: Test deployment

on:
  workflow_dispatch

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    name: Deploy and test
    steps:
      - uses: actions/checkout@v3
      - id: Test
        uses: structr/structr-deploy-action@v1.1-beta
        with:
          neo4j-version: '4.4'
          structr-version: '4.3-SNAPSHOT'
          structr-webapp-path: '${{ github.workspace }}/webapp'
          structr-conf-file: '${{ github.workspace }}/structr.conf'

      - name: "Run hello-world"
        run: curl -v localhost:8082/hello-world

      - name: Log docker-compose 
        run: cat ${{ github.workspace }}/docker-compose.yml
      
      - name: Log structr.conf contents
        run: cat ${{ github.workspace }}/structr.conf